### ISSUE TITLE
mkdir /conprof/wal: permission denied

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#151]
This was the result of me starting conprof with a freshly-created EBS volume.

I worked round it by running `chown -R nobody /conprof` on that volume as root, but is there a better way?

excerpts from config:
```
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
      storageClassName: gp2
      volumeMode: Filesystem
```

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

**Comment by brancz** [comment]
That's a bit odd indeed, which tag of the container image did you use?

**Comment by brancz** [comment]
Comparing with the Prometheus dockerfile, it looks like maybe we should try to change the `chown` command we have https://github.com/prometheus/prometheus/blob/7bf76af6dffc020fb7c4d489694bb8db0a223add/Dockerfile#L19

**Comment by brancz** [comment]
I have a suspicion about the ordering of commands in the dockerfile. I'll open a PR!

**Comment by brancz** [comment]
I think #153 should fix this, would you be able to test it one more time?

**Comment by bboreham** [comment]
I ran up a fresh install using `quay.io/conprof/conprof:master-2021-03-01-f8fd707` and it happened again.

**Comment by bboreham** [comment]
Note to self: this is how I kludged it, so I don't have to work this out again from scratch:

```
      initContainers:
      - name: chownvol
        image: bash
        args:
        - -c
        - "chown -R nobody /conprof"
        volumeMounts:
        - mountPath: /conprof
          name: storage
```

**Comment by brancz** [comment]
That's strange. I'm gonna have to get a test environment for this. Do you happen to know if the same thing happens for you with Prometheus?

**Comment by bboreham** [comment]
I have not tried the similar thing with Prometheus.
I suspect everything else I run with an EBS volume runs as root 😊

**Comment by jmichalek132** [comment]
Also ran into the issue I tried the image from manifests in this repository which is: `quay.io/brancz/conprof:08a162ee22cd`.

**Comment by jmichalek132** [comment]
I can reproduce it locally in k8s running using docker desktop.
Docker Engine version `v20.10.7`
Kubernetes version `v1.21.1`
Manifests used:
```
apiVersion: v1
kind: Namespace
metadata:
  name: conprof
  labels:
    name: conprof
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conprof
  namespace: conprof
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: conprof
  name: conprof
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: conprof
  name: conprof
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conprof
subjects:
  - kind: ServiceAccount
    name: conprof
    namespace: conprof
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
  name: conprof
  namespace: conprof
spec:
  volumeClaimTemplates:
    - metadata:
        name: conprof-tmp
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50.0Gi"
    - metadata:
        name: conprof-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "50.0Gi"
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
  serviceName: conprof
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: conprof
        app.kubernetes.io/name: conprof
    spec:
      containers:
      - args:
        - all
        - --log.level=debug
        - --storage.tsdb.path=/conprof
        - --config.file=/etc/conprof/conprof.yaml
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            configMapKeyRef:
              key: conprof.yaml
              name: conprof-objectstorage
        image: quay.io/brancz/conprof:08a162ee22cd
        name: conprof
        resources:
          requests:
            cpu: "1.0"
            memory: "2.0Gi"
            ephemeral-storage: "10.0Gi"
          limits:
            memory: "46.0Gi"
            cpu: "2.0"
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        volumeMounts:
        - mountPath: /tmp
          name: conprof-tmp
          readOnly: false
        - mountPath: /conprof
          name: conprof-data
          readOnly: false
        - mountPath: /etc/conprof
          name: config
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: conprof
      volumes:
      - name: config
        configMap:
          name: conprof
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
  name: conprof
  namespace: conprof
spec:
  clusterIP: None
  ports:
  - name: http
    port: 10902
    targetPort: http
  - name: grpc
    port: 10901
    targetPort: grpc
  selector:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
  name: conprof-objectstorage
  namespace: conprof
data:
  conprof.yaml: |-
    "config":
      "directory": "/tmp"
    "type": "FILESYSTEM"
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.medallia.com/team: "poe"
    app.medallia.com/environment: "demo"
  name: conprof
  namespace: conprof
data:
  conprof.yaml: |-
    "scrape_configs":
    - "job_name": "staging"
      "kubernetes_sd_configs":
      - "namespaces":
          "names":
          - "staging"
        "role": "pod"
      "relabel_configs":
      - "source_labels":
        - "__meta_kubernetes_namespace"
        "target_label": "namespace"
      - "source_labels":
        - "__meta_kubernetes_pod_name"
        "target_label": "pod"
      - "source_labels":
        - "__meta_kubernetes_pod_container_name"
        "target_label": "container"
      "scrape_interval": "1m"
      "scrape_timeout": "1m"
```
