### ISSUE TITLE
Improve profiling endpoint configuration

### ISSUE THREAD

**Issue by brancz** [conprof/conprof#165]
Right now it is next to impossible to add additional profiling endpoints such as `fgprof`. You need to modify an existing profile configuration that you don't care about like `threadcreate`:

```yaml
scrape_configs:
- job_name: 'kubernetes-pods'
  scrape_interval: 1m
  scrape_timeout: 1m
  profiling_config:
    pprof_config:
      threadcreate:
        path: /debug/fgprof
  kubernetes_sd_configs:
  - role: pod
    relabel_configs:
    - action: replace
      target_label: __param_seconds
      replacement: 3
    - action: labelmap
      regex: __meta_kubernetes_pod_label_app_kubernetes_io_(.+)
      replacement: "app_kubernetes_io_$1"
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: pod
    - source_labels: [__meta_kubernetes_pod_container_name]
      action: replace
      target_label: container
```

A proposal could be to instead of having hardcoded profile name values under `pprof_config` use `map[string]PprofProfilingConfig` instead and merge what the user passes on top of the default. That way there is a reasonable default as well as the possibility to extend.

cc @metalmatze @cyriltovena
