### ISSUE TITLE
Storage usage

### ISSUE THREAD

**Issue by weeco** [conprof/conprof#34]
Hey,
I ran conprof with this config:

```yaml
scrape_configs:
  - job_name: conprof
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_conprof_scrape]
        action: keep
        regex: true
      - source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
    scrape_interval: 1m
    scrape_timeout: 1m
```

and I attached a 500Gig persistent volume which it uses to write it's data to. The config targets 10 pods and it took only 3-4 hours until the 500Gig were completely full. Is this expected / what do you recommend to configure so that conprof doesn't need that much storage?
