### ISSUE TITLE
How to support fgprof endpoint?

### ISSUE THREAD

**Issue by yeya24** [conprof/conprof#69]
Recently [fgprof](https://github.com/felixge/fgprof) is added to Thanos in endpoint `/debug/fgprof`. I am wondering how to enable scraping this endpoint at the same time with `profile`.

`fgprof` is similar to pprof profile, so I can configure something like below to enable fgprof, but this cannot enable profile at the same time.

```
scrape_configs:
- job_name: 'conprof'
  scrape_interval: 1m
  scrape_timeout: 1m
  profiling_config:
    pprof_config:
      profile:
        path: /debug/fgprof
        enabled: true
  static_configs:
  - targets: ['localhost:6060']
```

**Comment by brancz** [comment]
Yeah, I've been thinking about this as well, I haven't made up my mind about it yet. An escape could be "additional profiles" that are basically free form, or maybe any profile should be free form, instead of the predefined ones we have right now. What do you think?

**Comment by povilasv** [comment]
I'm on similiar boat, the only exception is the tracing part which is not actually pprof. So maybe there should be two types, pprof and tracing?

**Comment by brancz** [comment]
I'd be curious to know if we could instead "discover" the profiles a target has available. Naively this should be pretty straight forward if all profiles are registered and visible in the `/debug/pprof` index page. It does appear that this could be possible if [`pprof.Profiles()`](https://golang.org/src/net/http/pprof/pprof.go?s=11657:11707#L353) returns custom profiles as well. It does look like [`pprof.NewProfile`](https://golang.org/src/runtime/pprof/pprof.go?s=6806:6843#L198) does register new profiles created. It doesn't look like fgprof currently does this, but I think it's worth investigating.

**Comment by bwplotka** [comment]
On related note, do we really need to collect always all type of profiles / pprof resources?

What about overall, ability to specify which profiles to scrape per scrape job? :thinking: Would this be useful @brancz ? 

This will satisfy fgprof and maybe extra, other profiles someone can have. Of course by default, if not set we can use discovery like you proposed (:

**Comment by brancz** [comment]
It's already configurable but defaults to all.

**Comment by bwplotka** [comment]
I see. Adding fgprof to conprof as well so we can play with it: https://github.com/conprof/conprof/pull/74

**Comment by syepes** [comment]
@brancz What would be the basic scrape config to collect all the profiles including the fgprof?

**Comment by brancz** [comment]
Currently that's not really possible, what you can do though is change the `profile` endpoint (the "normal" cpu profile to be `/debug/fgprof`. I'm still discussing with the go team if we can find a solution that would allow us to auto-discover the profiles available, should that not lead anywhere though, then we can discuss other strategies I would say.

**Comment by metalmatze** [comment]
In the mean time I've worked on #165 and #169 was just merged allowing to add more custom profile types.
This works now:
```yaml
  - job_name: 'awesome-app'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:10902' ]
    profiling_config:
      pprof_config:
        ...
        fgprof:
          enabled: true
          path: /debug/fgprof
```
Adding the last part conprof should start scraping that endpoint now too. Let me know if you have problems if not.
